# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='click',
            name='user',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='click',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
