# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url_app', '0002_auto_20160618_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
