# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url_app', '0002_auto_20160617_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
