# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_url_app', '0004_bookmark_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='click',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
